name: PR Info from Commit
description:
  Retrieves Pull Request information associated with a commit SHA from a Push
  Event
author: Dennis Cual

branding:
  icon: git-pull-request
  color: blue

inputs:
  commit_sha:
    description: The commit SHA from the push event
    required: true
  github_token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}

outputs:
  pull_request_number:
    description: The number of the pull request associated with the commit
  pull_request_title:
    description: The title of the pull request
  pull_request_url:
    description: The URL of the pull request
  pull_request_labels:
    description: JSON array of labels on the pull request

runs:
  using: node20
  main: dist/index.js
