name: PR Info from Commit
description:
  Retrieves Pull Request information associated with a commit SHA from a Push
  Event
author: Dennis Cual

branding:
  icon: git-pull-request
  color: blue

inputs:
  commit_sha:
    description: The commit SHA from the push event
    required: true
  github_token:
    description: GitHub token for API access
    required: true
  owner:
    description: The owner of the repository
    required: true
  repo:
    description: The name of the repository
    required: true

outputs:
  pull_requests:
    description: JSON array of pull requests associated with the commit

runs:
  using: node20
  main: dist/index.js
